# Generated by Django 4.2.30 on 2026-05-22 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotooRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(auto_now_add=True, verbose_name='추첨 날짜')),
                ('num1', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호 1')),
                ('num2', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호 2')),
                ('num3', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호 3')),
                ('num4', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호 4')),
                ('num5', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호 5')),
                ('num6', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호 6')),
                ('bonus_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='보너스 번호')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], max_length=6, verbose_name='선택 유형')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 날짜')),
                ('num1', models.PositiveIntegerField(verbose_name='번호 1')),
                ('num2', models.PositiveIntegerField(verbose_name='번호 2')),
                ('num3', models.PositiveIntegerField(verbose_name='번호 3')),
                ('num4', models.PositiveIntegerField(verbose_name='번호 4')),
                ('num5', models.PositiveIntegerField(verbose_name='번호 5')),
                ('num6', models.PositiveIntegerField(verbose_name='번호 6')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='당첨 등수')),
                ('is_checked', models.BooleanField(default=False, verbose_name='당첨 여부 확인')),
                ('round_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.lotooround', verbose_name='회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
    ]
