# Generated by Django 4.2.30 on 2026-05-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LotooRound',
            new_name='LottoRound',
        ),
    ]
